
build:
  version: "2.0"

product:
  message: "Welcome to product service related local QA APIs"
  contactDetails:
    name: "Manoj - Technical QA Lead"
    email: "manoj@practice.com"
  onCallSupport:
    - +919884137236