build:
  version: "3.0"

accounts:
  message: "Welcome to E-Sale products related docker APIs "
  contactDetails:
    name: "John Doe - Developer"
    email: "john@esale.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 523-1345
