
build:
  version: "1.0"

product:
  message: "Welcome to product service related local PROD APIs"
  contactDetails:
    name: "Manoj - Technical PROD Lead"
    email: "manoj@practice.com"
  onCallSupport:
    - +919884137236